apiVersion: v1
kind: Namespace
metadata:
  name: open-cluster-management
  labels:
    app.kubernetes.io/part-of: mlops-edge
    app.kubernetes.io/component: acm
    scenario: scenario-01-full-openshift

