receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'node_exporter'
          static_configs:
            - targets: ['localhost:9100']

processors:
  batch:
    timeout: 10s

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"

  otlp:
    endpoint: "flightctl-telemetry-gateway:4317"
    tls:
      ca_file: /etc/otelcol/certs/ca.crt
      cert_file: /etc/otelcol/certs/otel.crt
      key_file: /etc/otelcol/certs/otel.key

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [prometheus, otlp]