apiVersion: v1
kind: Namespace
metadata:
  name: redhat-ods-operator
  labels:
    app.kubernetes.io/part-of: mlops-edge
    app.kubernetes.io/component: openshift-ai
    scenario: scenario-02-device-edge

