apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipeline-workspace
  namespace: mlops-pipelines
  labels:
    app.kubernetes.io/part-of: mlops-edge
    app.kubernetes.io/component: pipelines
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Namespace
metadata:
  name: mlops-pipelines
  labels:
    app.kubernetes.io/part-of: mlops-edge
    app.kubernetes.io/component: pipelines
