apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: $DEVICE_NAME
  namespace: $FLEET_NAMESPACE
spec:
  runStrategy: Always
  instancetype:
    name: flightctl-device
    kind: VirtualMachineInstancetype
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: mlops-edge
    spec:
      # node selector field might be useful for gpu part
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: $FLIGHTCTL_CONTAINERDISK_IMAGE
            imagePullPolicy: Always
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef:
              name: flightctl-cloud-init