apiVersion: flightctl.io/v1beta1
kind: Fleet
metadata:
  name: mlops
spec:
  selector:
    matchLabels:
      project: mlops
  template:
    metadata:
      labels:
        fleet: mlops
    spec:
      applications:
        - name: mlops-gpu-stack
          appType: quadlet
          image: quay.io/redhat-et/mlops-quadlet:v1.0.0
      config:
      - name: inference-server-metrics
        gitRef: 
          repository: mlops-at-the-edge
          targetRevision: observability
          path: scenarios/scenario-02-device-edge/flightctl/configs
